global:
  smtp_smarthost: "smtp.sendgrid.net:465"
  smtp_from: "noreply@alertmanager.com"
  smtp_auth_username: "apikey"
  smtp_auth_password: "demo"
  smtp_require_tls: false

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "discord"

receivers:
  - name: "web.hook"
    webhook_configs:
      - url: http://127.0.0.1:5001

  - name: "email"
    email_configs:
      - to: "demo@demo.com"
        send_resolved: true

  - name: "discord"
    discord_configs:
      - webhook_url: "https://discord.com/api/webhooks/xxx" # add your webhook
        send_resolved: true
        title: '{{ template "discord.default.title" . }}'
        message: '{{ template "discord.default.message" . }}'

  - name: "telegram"
    telegram_configs:
      - send_resolved: true
        message: '{{ template "telegram.default.message" . }}'
        bot_token: "xxx"
        chat_id: -1

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
